In [642]:
#import needed library: pandas,nump and matplot
import numpy as np
import pandas as pd
import matplotlib as plt

In [680]:
#get the train file
datatrain = pd.read_csv("train.csv")

In [681]:
#change display options
pd.options.display.max_columns = 150
pd.options.display.max_rows = 150

In [683]:
#Show datatest info
datatrain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9557 entries, 0 to 9556
Columns: 143 entries, Id to Target
dtypes: float64(8), int64(130), object(5)
memory usage: 10.4+ MB


In [685]:
#So there is a five objects, let's see if there is null values
datatrain.isna().sum()

Id                    0
v2a1               6860
hacdor                0
rooms                 0
hacapo                0
v14a                  0
refrig                0
v18q                  0
v18q1              7342
r4h1                  0
r4h2                  0
r4h3                  0
r4m1                  0
r4m2                  0
r4m3                  0
r4t1                  0
r4t2                  0
r4t3                  0
tamhog                0
tamviv                0
escolari              0
rez_esc            7928
hhsize                0
paredblolad           0
paredzocalo           0
paredpreb             0
pareddes              0
paredmad              0
paredzinc             0
paredfibras           0
paredother            0
pisomoscer            0
pisocemento           0
pisoother             0
pisonatur             0
pisonotiene           0
pisomadera            0
techozinc             0
techoentrepiso        0
techocane             0
techootro             0
cielorazo       

In [686]:
#As we saw there is a five coulmns that have a missings values 
#Handling missing values in v18q1 it's by replacing NaN values => Zeros
datatrain['v18q1'].replace(np.NaN,0,inplace=True)

In [687]:
datatrain.groupby('instlevel9')['meaneduc'].mean()

instlevel9
0     9.121911
1    16.244444
Name: meaneduc, dtype: float64

In [688]:
#For Handling missing values in meaneduc we make an imputer to do that like follows:
def impute_meaneduc(coulmns):
    meaneduc = coulmns[0]
    instlevel9 = coulmns[1]
    if pd.isna(meaneduc):
        if instlevel9 == 0:
            meaneduc = 9.121911
        elif instlevel9 == 1:
            meaneduc = 16.244444
    return meaneduc

In [689]:
#Apply 'meaneduc' column on impute_meaneduc function
datatrain['meaneduc'] = datatrain[['meaneduc','instlevel9']].apply(impute_meaneduc, axis=1)

In [691]:
#For Handling missing values in 'SQBmeaned' which is the square root for 'meaneduc' like follows:
datatrain['SQBmeaned'].replace(np.NaN,datatrain['meaneduc']**2, inplace = True)

In [693]:
datatrain.groupby(['age'])['rez_esc'].mean()

age
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7     0.000000
8     0.036765
9     0.071429
10    0.167883
11    0.195489
12    0.302158
13    0.266234
14    0.288732
15    0.686275
16    1.116667
17    1.457143
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23         NaN
24         NaN
25         NaN
26         NaN
27         NaN
28         NaN
29         NaN
30         NaN
31         NaN
32         NaN
33         NaN
34         NaN
35         NaN
36         NaN
37         NaN
38         NaN
39         NaN
40         NaN
41         NaN
42         NaN
43         NaN
44         NaN
45         NaN
46         NaN
47         NaN
48         NaN
49         NaN
50         NaN
51         NaN
52         NaN
53         NaN
54         NaN
55         NaN
56         NaN
57         NaN
58         NaN
59         NaN
60         NaN
61         NaN
62         NaN
63         NaN
64         NaN
65         NaN
66    

In [694]:
datatrain.groupby(['escolari'])['rez_esc'].mean()

escolari
0     0.173077
1     0.125000
2     0.251497
3     0.356061
4     0.291667
5     0.363014
6     1.150215
7     0.676768
8     0.615894
9     0.309091
10    0.000000
11    0.000000
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN
Name: rez_esc, dtype: float64

In [695]:
#For Handling missing values in 'rez_esc' we make an imputer to do that like follows:
def impute_rez_esc(coulmns):
    rez_esc = coulmns[0]
    age = coulmns[1]
    escolari = coulmns[2]
    if pd.isna(rez_esc):
        if age < 7:
            return 0
        else:
            return age-escolari-7
    return rez_esc

In [697]:
#Apply 'rez_esc' column on impute_rez_esc function
datatrain['rez_esc'] = datatrain[['rez_esc','age','escolari']].apply(impute_rez_esc, axis=1)

In [698]:
datatrain.groupby(['rooms','paredpreb','pisonotiene'])['v2a1'].mean()

rooms  paredpreb  pisonotiene
1      0          0               76666.666667
                  1               15000.000000
       1          0               55379.285714
2      0          0               93342.333333
                  1                        NaN
       1          0               95000.000000
3      0          0              122383.138614
                  1               65000.000000
       1          0               97794.750000
4      0          0              126042.299492
                  1                        NaN
       1          0              101857.244681
                  1                        NaN
5      0          0              157051.669444
                  1                        NaN
       1          0              137608.695652
6      0          0              230395.127451
                  1                        NaN
       1          0               93108.000000
7      0          0              287232.601399
                  1           

In [699]:
#For Handling missing values in 'v2a1' we make an imputer to do that like follows:
def impute_v2a1(coulmns):
    v2a1 = coulmns[0]
    rooms = coulmns[1]
    paredpreb = coulmns[2]
    pisonotiene = coulmns[3]
    if pd.isna(v2a1):
        if rooms == 1:
            if paredpreb == 0:
                if pisonotiene == 0:
                    return 76667
                elif pisonotiene == 1:
                    return 15000
            elif paredpreb == 1:
                return 55378
        elif rooms == 2:
            if paredpreb == 0:
                return 93342
            elif paredpreb == 1:
                return 95342
        elif rooms == 3:
            if paredpreb == 0:
                if pisonotiene == 0:
                    return 122383
                elif pisonotiene == 1:
                    return 65000
            elif paredpreb == 1:
                return 97795
        elif rooms == 4:
            if paredpreb == 0:
                return 126042
            elif paredpreb == 1:
                return 101857
        elif rooms == 5:
            if paredpreb == 0:
                return 157052
            elif paredpreb == 1:
                return 137609
        elif rooms == 6:
            if paredpreb == 0:
                return 230395
            elif paredpreb == 1:
                return 93108
        elif rooms == 7:
            return 287232
        elif rooms == 8:
            if paredpreb == 0:
                return 434370
            elif paredpreb == 1:
                return 200000
        elif rooms == 9:
            return 605221
        elif rooms == 10:
            return 570540
        else:
            return 600000
    return v2a1

In [701]:
#Apply 'v2a1' column on impute_v2a1 function
datatrain['v2a1'] = datatrain[['v2a1','rooms','paredpreb','pisonotiene']].apply(impute_v2a1, axis = 1)

In [704]:
#Droping unwanted coulmns
datatrain.drop(['Id','idhogar'], axis = 1, inplace = True)

In [706]:
#Now For deails with the three objects remaining, first we will change yes->1, no->0 then convert the column to float
datatrain['dependency'].replace('no',0, inplace = True)
datatrain['dependency'].replace('yes',1, inplace = True)
datatrain['edjefa'].replace('no',0, inplace = True)
datatrain['edjefa'].replace('yes',1, inplace = True)
datatrain['edjefe'].replace('no',0, inplace = True)
datatrain['edjefe'].replace('yes',1, inplace = True)

# convert object coulmn to float column
datatrain.iloc[:,98:99] = datatrain.iloc[:,98:99].astype(str).astype(float)
datatrain.iloc[:,99:100] = datatrain.iloc[:,99:100].astype(str).astype(float)
datatrain.iloc[:,100:101] = datatrain.iloc[:,100:101].astype(str).astype(float)


In [707]:
#Now spiling the data file to test the concarrency with the target 
x = datatrain.iloc[:,:-1]
y = datatrain.iloc[:,-1]

In [708]:
#split 80% of data train to test and the rest to train
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [709]:
datatrain['instlevel1'].replace(np.NaN,0,inplace=True)

In [710]:
#trying KNN machine learning algorithm for training
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=200,metric='minkowski',p=1)
classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=200, p=1,
           weights='uniform')

In [711]:
#Now the algorithm will predict the Target
y_pred = classifier.predict(x_test)

In [712]:
#Here we will check the percentage of valid data
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred,y_test)


In [713]:
print(cm)

[[   0    0    0    0]
 [   0    0    0    0]
 [   0    0    0    0]
 [ 151  331  246 1184]]


In [714]:
correct = cm[0][0]+cm[1][1]+cm[2][2]+cm[3][3]
print(correct)


1184


In [715]:
total = 0
for i in range (0,4):
    for j in range (0,4):
        if i==j:
            continue
        total +=cm[i][j]
total+=correct
print(total)


1912


In [716]:
correct_percentage = correct/total
print(correct_percentage)

0.6192468619246861


In [717]:
#trying RandomForest machine learning algorithm for training
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=200,criterion='entropy')
classifier.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [718]:
#Now the algorithm will predict the Target
y_pred = classifier.predict(x_test)

In [719]:
#Here we will check the percentage of valid data
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred,y_test)
print(cm)

[[ 110    5    1    0]
 [  15  279    5    2]
 [   0    5  194    3]
 [  26   42   46 1179]]


In [720]:
correct = cm[0][0]+cm[1][1]+cm[2][2]+cm[3][3]
print(correct)


1762


In [721]:
total = 0
for i in range (0,4):
    for j in range (0,4):
        if i==j:
            continue
        total +=cm[i][j]
total+=correct
print(total)


1912


In [722]:
correct_percentage = correct/total
print(correct_percentage)

0.9215481171548117


In [724]:
from xgboost import XGBClassifier
classifier = XGBClassifier(max_depth=100, n_estimators=500, learning_rate=0.2)
classifier.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.2, max_delta_step=0,
       max_depth=100, min_child_weight=1, missing=None, n_estimators=500,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [725]:
#Now the algorithm will predict the Target
y_pred = classifier.predict(x_test)

In [726]:
#Here we will check the percentage of valid data
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred,y_test)
print(cm)

[[ 127    5    1    0]
 [  14  304    6    4]
 [   2    5  226    8]
 [   8   17   13 1172]]


In [727]:
correct = cm[0][0]+cm[1][1]+cm[2][2]+cm[3][3]
print(correct)


1829


In [728]:
total = 0
for i in range (0,4):
    for j in range (0,4):
        if i==j:
            continue
        total +=cm[i][j]
total+=correct
print(total)


1912


In [729]:
correct_percentage = correct/total
print(correct_percentage)

0.9565899581589958


In [730]:
#trying Lightgbm machine learning algorithm for training
import lightgbm as lgb
classifier = lgb.Dataset(x_train,label=y_train)

In [731]:
#Using this parameters
params = {}
params['learning_rate']= 0.20
params['n_estimators'] = 500
params['num_leaves']= 1000
params['max_depth']=100

In [732]:
clf = lgb.train(params, classifier)

C:\Users\User\Anaconda3\lib\site-packages\lightgbm\engine.py:116: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))


In [733]:
y_pred = clf.predict(x_test)

In [734]:
y_pred = [round(i) for i in y_pred]

In [735]:
#Here we will check the percentage of valid data
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred,y_test)
print(cm)

[[ 107    5    0    0    0]
 [  33  284    4    3    0]
 [   7   38  237   69    0]
 [   4    4    5 1110    0]
 [   0    0    0    2    0]]


In [736]:
correct = cm[0][0]+cm[1][1]+cm[2][2]+cm[3][3]
print(correct)


1738


In [737]:
total = 0
for i in range (0,4):
    for j in range (0,4):
        if i==j:
            continue
        total +=cm[i][j]
total+=correct
print(total)


1910


In [738]:
correct_percentage = correct/total
print(correct_percentage)

0.9099476439790576


In [739]:
# SO from this result we saw that the XGBoost is better than other
# Part two will be based on XGBoost